name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel build-essential git libffi-dev libssl-dev libncurses5 libncurses5-dev libtinfo5 libtinfo-dev
        python3 -m pip install --upgrade pip
        pip install cython virtualenv
        pip install buildozer

    - name: Initialize buildozer
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: kivy-apk
        path: bin/*.apk
